enum Path {
  LandingPage = '/',
  AdminPage = '/35D648E599E6DEBBA04060C6DA86C5B64A5975966C4F2D3170B0CE457BE78BE2',
  TestLogin = '/test-login',
  Component = '/component', // FIXME: 컴포넌트 모아두는 곳 (개발완료 후 삭제)
  AuthMail = '/auth-mail',
  TypeOfMeetingSurvey = '/type-of-meeting',
  GenderAverageAgeSurvey = 'gender-age',
  OurUniversitiesSurvey = 'our-univ',
  OurDepartmentsAverageHeightSurvey = 'our-dprt-height',
  AvoidUniversitiesSurvey = 'avoid-univ',
  PreferUniversitiesSurvey = 'prefer-univ',
  PreferAgeHeightSurvey = 'prefer-age-height',
  PreferDepartmentsSurvey = 'prefer-dprt',
  MindsetSurvey = 'mindset',
  PlaySurvey = 'play',
  IsAbroadSurvey = 'isabroad',
  DomesticAreasSurvey = 'dmst-area',
  AbroadAreasSurvey = 'abroad-area',
  ChannelSurvey = 'channel',
  AgreementSurvey = 'agreement',
  KakaoIdSurvey = 'kakao-id',
  MyGenderAge = 'my-gender-age',
  MyDepartmentCharacter = 'my-department-character',
  MyMbtiHeight = 'my-mbti-height',
  MyBodySmoke = 'my-body-smoke',
  MyDateCount = 'my-date-count',
  PreferDepartmentCharacterSurvey = 'prefer-dprt-character',
  PreferBodyDateCountSurvey = 'prefer-body-dcount',
  OauthKakao = '/oauth/kakao',
  MatchingMeeting = '/matching/meeting',
  MatchingDating = '/matching/dating',
}

export default Path;
